import pytesseract
from PIL import Image
import glob
import re

DIR = "dataset/examples/"

def get_captcha_text(image):
    """
    This function will handle the core OCR processing of the captcha.
    """

    # OCR
    captcha_text = pytesseract.image_to_string(image)

    # Text pre-processing
    captcha_text = captcha_text.replace('O','0') # Replace O because captcha only contains 0
    captcha_text = captcha_text.replace(' ','') # Remove any whitespace generated by the OCR

    r = re.compile('[^a-zA-Z0-9]')
    captcha_text = r.sub('',captcha_text) # Remove any non-alphanumeric character 
    captcha_text = captcha_text.upper() # Convert any lowercase into uppercase

    if len(captcha_text) > 6:
    	captcha_text = captcha_text[:len(captcha_text)-6]

    return captcha_text

images=glob.glob(DIR+"*.png")

for image in images:
    img = Image.open(image)
    print(get_captcha_text(img))